name: Deploy To Render

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Render Deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
